config/routes.rb
Rails.application.routes.draw do
  resources :links

  
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      get 'object/:id' => 'key_value_api#find'
      post 'object' => 'key_value_api#create'
    end
  end

end

app/models/keyvalue.rb
class Keyvalue < ActiveRecord::Base
end

app/controllers/api/v1/base_api_controller.rb
module Api
  module V1
    class BaseApiController < ActionController::Base

    end
  end
end

app/controllers/api/v1/key_value_api_controller.rb
module Api
  module V1

    class KeyValueApiController < BaseApiController

      respond_to :json

      def create
        
        key = params.keys[0]
        value = params[key]
        
        if key
          key_value = Keyvalue.new
          key_value.key = key
          key_value.value = value
          if key_value.save
            render json: key_value
          else
            render nothing: true, status: :bad_request
          end
        else
          render nothing: true, status: :bad_request
        end
        
      end
      
      def find
        
        begin
          
          timestamp = params[:timestamp]
          
          if(timestamp)
            updated = Time.at(timestamp.to_i)
            render json: Keyvalue.where("key = ? AND updated_at >= ?", params[:id], updated).first
          else
            key_value = Keyvalue.where(key: params[:id]).last
            render :text => key_value.value
          end
          
        rescue Exception => e  
          
          render json: {error: e.message}
          
        end
               
      end

    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Urlshortener</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/links/_form.html.erb
<%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form' %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/go.html.erb
<script type="text/javascript">
  window.location.href="<%= @link.url %>"  // put your correct path in a string here
</script>

app/views/links/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Links</h1>

<table>
  <thead>
    <tr>
      <th>Url</th>
      <th>Shortened</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @links.each do |link| %>
      <tr>
        <td><%= link.url %></td>
        <td><%= link.shortened_url %></td>
        <td><%= link_to 'Show', link %></td>
        <td><%= link_to 'Edit', edit_link_path(link) %></td>
        <td><%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Link', new_link_path %>

app/views/links/new.html.erb
<h1>New Link</h1>

<%= render 'form' %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @link.url %>
</p>

<p>
  <strong>Shortened url:</strong>
  <%= @link.shortened_url %>
</p>

<%= link_to 'Edit', edit_link_path(@link) %> |
<%= link_to 'Back', links_path %>